import Head from "next/head";
import Link from "next/link";
import { Plus_Jakarta_Sans } from "next/font/google"
import Hero from "~/components/Hero";
import Bio from "~/components/Bio";
import Works from "~/components/Works";
import Contact from "~/components/Contact";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: '--font-jakarta'
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${jakarta.variable}` + " flex min-h-screen flex-col items-center justify-center bg-[var(--lewis-color)] font-sans gap-[100px] p-4"}>
        <Hero />
        <Bio />
        <Works />
        <Contact />
      </main>
    </>
  );
}
